# taken from: https://stackoverflow.com/questions/37221483/kubernetes-service-located-in-another-namespace
# use case: connect from node to mongo db in other namespace
# other solution: deploy github bot & analyzer in mongo db namespace & call frontend service with post


#Each pod in a StatefulSet backed by a Headless Service will have a stable DNS name. The template follows this format: <pod-name>.<service-name>
 #
 #This means the DNS names for the MongoDB replica set are:

# mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/dbname_?
#mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
# taken from: https://docs.mongodb.com/manual/reference/connection-string/

# PROBLEM: node frontend not allowed to acces mongo-headless-service directly but need to go over this router service -> how does the connection string then look like?
# e.g mongodb://servicerouter/mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/dbname_?
kind: Service
apiVersion: v1
metadata:
  name: service-y
  namespace: namespace-a
spec:
  type: ExternalName
  externalName: service-x.namespace-b.svc.cluster.local
  ports:
  - port: 80